### ISSUE TITLE
make WIN64=yes fails on build. (Linux MinGW cross-compile)

### ISSUE THREAD

**Issue by stan0x** [Raptor007/aq2-tng#100]
seems to give some erroors in tng_irc.o:tng_irc.c.

also doenst seem to make a .dll file

src/acebot_spawn.o acesrc/bot_env_doors.o acesrc/bot_utility.o acesrc/acebot_compress.o acesrc/bot_ai.o acesrc/bot_movement.o acesrc/bot_weapon.o acesrc/acebot_items.o acesrc/botchat.o acesrc/botnav.o acesrc/acebot_movement.o acesrc/bot_collision.o acesrc/botscan.o
/usr/bin/x86_64-w64-mingw32-ld: tng_irc.o:tng_irc.c:(.text+0x1c): undefined reference to `__imp_socket'
/usr/bin/x86_64-w64-mingw32-ld: tng_irc.o:tng_irc.c:(.text+0x59): undefined reference to `__imp_setsockopt'
/usr/bin/x86_64-w64-mingw32-ld: tng_irc.o:tng_irc.c:(.text+0x80): undefined reference to `__imp_htons'
/usr/bin/x86_64-w64-mingw32-ld: tng_irc.o:tng_irc.c:(.text+0x97): undefined reference to `__imp_bind'
/usr/bin/x86_64-w64-mingw32-ld: tng_irc.o:tng_irc.c:(.text+0xae): undefined reference to `__imp_listen'
/usr/bin/x86_64-w64-mingw32-ld: tng_irc.o:tng_irc.c:(.text+0xce): undefined reference to `__imp_accept'
/usr/bin/x86_64-w64-mingw32-ld: tng_irc.o:tng_irc.c:(.text+0xd5): undefined reference to `__imp_closesocket'
/usr/bin/x86_64-w64-mingw32-ld: tng_irc.o:tng_irc.c:(.text+0x11e): undefined reference to `__imp_recv'
/usr/bin/x86_64-w64-mingw32-ld: tng_irc.o:tng_irc.c:(.text+0x1d1): undefined reference to `__imp_send'
/usr/bin/x86_64-w64-mingw32-ld: tng_irc.o:tng_irc.c:(.text+0x1fd): undefined reference to `__imp_closesocket'
/usr/bin/x86_64-w64-mingw32-ld: tng_irc.o:tng_irc.c:(.text+0x229): undefined reference to `__imp_inet_ntoa'
/usr/bin/x86_64-w64-mingw32-ld: tng_irc.o:tng_irc.c:(.text+0x25d): undefined reference to `__imp_send'
/usr/bin/x86_64-w64-mingw32-ld: tng_irc.o:tng_irc.c:(.text+0x2e3): undefined reference to `__imp_WSAStartup'
/usr/bin/x86_64-w64-mingw32-ld: tng_irc.o:tng_irc.c:(.text+0x550): undefined reference to `__imp_htons'
/usr/bin/x86_64-w64-mingw32-ld: tng_irc.o:tng_irc.c:(.text+0x5d4): undefined reference to `__imp_inet_addr'
/usr/bin/x86_64-w64-mingw32-ld: tng_irc.o:tng_irc.c:(.text+0x681): undefined reference to `__imp_ntohs'
/usr/bin/x86_64-w64-mingw32-ld: tng_irc.o:tng_irc.c:(.text+0x691): undefined reference to `__imp_inet_ntoa'
/usr/bin/x86_64-w64-mingw32-ld: tng_irc.o:tng_irc.c:(.text+0x6dc): undefined reference to `__imp_socket'
/usr/bin/x86_64-w64-mingw32-ld: tng_irc.o:tng_irc.c:(.text+0x739): undefined reference to `__imp_gethostbyname'
/usr/bin/x86_64-w64-mingw32-ld: tng_irc.o:tng_irc.c:(.text+0x74d): undefined reference to `__imp_inet_ntoa'
/usr/bin/x86_64-w64-mingw32-ld: tng_irc.o:tng_irc.c:(.text+0x76e): undefined reference to `__imp_connect'
/usr/bin/x86_64-w64-mingw32-ld: tng_irc.o:tng_irc.c:(.text+0x84f): undefined reference to `__imp_ioctlsocket'
/usr/bin/x86_64-w64-mingw32-ld: tng_irc.o:tng_irc.c:(.text+0x8cd): undefined reference to `__imp_send'
/usr/bin/x86_64-w64-mingw32-ld: tng_irc.o:tng_irc.c:(.text+0xa04): undefined reference to `__imp_send'
/usr/bin/x86_64-w64-mingw32-ld: tng_irc.o:tng_irc.c:(.text+0xc3e): undefined reference to `__imp_send'
/usr/bin/x86_64-w64-mingw32-ld: tng_irc.o:tng_irc.c:(.text+0xdd3): undefined reference to `__imp_send'
/usr/bin/x86_64-w64-mingw32-ld: tng_irc.o:tng_irc.c:(.text+0x129c): undefined reference to `__imp_send'
/usr/bin/x86_64-w64-mingw32-ld: tng_irc.o:tng_irc.c:(.text+0x134d): more undefined references to `__imp_send' follow
/usr/bin/x86_64-w64-mingw32-ld: tng_irc.o:tng_irc.c:(.text+0x1acd): undefined reference to `__imp_recv'
/usr/bin/x86_64-w64-mingw32-ld: tng_irc.o:tng_irc.c:(.text+0x1c59): undefined reference to `__imp_WSAGetLastError'
/usr/bin/x86_64-w64-mingw32-ld: tng_irc.o:tng_irc.c:(.text+0x1e5e): undefined reference to `__imp_send'
collect2: error: ld returned 1 exit status
make: *** [Makefile:118: gamex86_64.so] Error 1

**Comment by Raptor007** [comment]
It should detect your MinGW environment and set `WIN32=y` automatically, which would add `-lws2_32` to the linker step and solve those errors.  For now, you should be able to build a 64-bit DLL with `make WIN32=y WIN64=y` as a workaround.

What does it say when you type `uname -s` in MinGW?  That should tell me what I need to know to fix the Makefile.

(Be aware most Windows q2pro.exe builds are 32-bit, so you may not actually need a 64-bit DLL.)

**Comment by stan0x** [comment]
I added some to the Makefile. Now it works on 32bit and 64bit. #101

**Comment by Raptor007** [comment]
Sorry for the delay!  I merged these changes today, and tweaked them so they won't break the build process on Windows MinGW.

https://github.com/Raptor007/aq2-tng/commit/6f4e934bd298b2203f6fb1fb5f9663749d882c2a
