### ISSUE TITLE
CTF matchmode bug

### ISSUE THREAD

**Issue by m4son** [Raptor007/aq2-tng#105]
After CTF match is finished in a matchmode, if we ready up again, it doesn't switch teams after half the timelimit. But if we do resetscores it's as it should be.

**Comment by Raptor007** [comment]
Interesting.  Probably related to issue #80.  At a quick glance, I suspect it needs `teams_changed = false` when the match ends.

**Comment by Raptor007** [comment]
I tried to recreate this problem with `ctf 1` `matchmode 1` but was unable to.  Whether the map was changed by `votemap`, `gamemap`, or `map`, the teams still swap correctly at every halftime.  I also tried with both `auto_join 0` and `auto_join 1`.  The only quirk is that with `auto_join 1`, the teams you are swapped to at halftime become your starting teams for the next map.  But they do correctly swap back at halftime, so this isn't really a problem.

I also looked into the `teams_changed` variable.  It's just used to update the join menu, and will get changed to false in ClientEndServerFrames on the next FRAMESYNC:
https://github.com/Raptor007/aq2-tng/blob/7fcea7db86db9087bd9217f50db31ca9bdbb7792/source/g_main.c#L602-L609

Let me know if you are still having this problem.  Maybe some other code cleanup fixed this accidentally.

**Comment by m4son** [comment]
We did not change the map, just ready up again. Going to try again.

**Comment by Raptor007** [comment]
Ah thanks, now I understand.  I'll try again.

**Comment by m4son** [comment]
Ops, I forgot to test but it seems like you found the problem too!
