### ISSUE TITLE
Tourney mode: Countdown at the beginning of rounds

### ISSUE THREAD

**Issue by lowkeyau** [Raptor007/aq2-tng#110]
Hey,

Currently there's no countdown (that we can enable) prior to a round starting in tourney mode. It's a silent no shoot/no fall dmg for 5(?) seconds.

Is there any way to implement this into tourney ala normal team mode?

Thanks,

**Comment by Raptor007** [comment]
Oh, it's just silent?  Not even "Lights Camera Action"?

Would you like it to have the full "10, 9, 8..." countdown?

I have to admit I don't really use tournament mode, but I can still fix it if it's not behaving as expected or desired.

**Comment by lowkeyau** [comment]
Thanks, really appreciated.

There's no count down or 'lights camera action'. 

I think 'lights camera action' would be great if possible.

We're trying tourney to see if it plays well as the communities quite small at the moment.

**Comment by Raptor007** [comment]
Hey @lowkeyau I'm closing this issue assuming @darkshade9's fix works for you, which has now been merged upstream.  If not, please feel free to reopen it.
