### ISSUE TITLE
Warmup crash fix and enhancements.

### ISSUE THREAD

**Issue by Raptor007** [Raptor007/aq2-tng#15]
_Original issue title: Fix warmup mode crash._

I've been told that when a server has lots of people, the warmup mode can crash the server.

**Comment by Raptor007** [comment]
Warmup commits: https://github.com/Raptor007/aq2-tng/commit/0c03e6eab4cb95d5a57d40cc9b09c2f70bd80227 https://github.com/Raptor007/aq2-tng/commit/c48a4ff7243b3680142da2d3cad7da8468ecdc90 https://github.com/Raptor007/aq2-tng/commit/5383b30fa08ac721b05c04a97b02af946e02af18

**Comment by Raptor007** [comment]
If this is related to `transparent_list`, it's possible this was fixed when #36 got fixed: https://github.com/Raptor007/aq2-tng/commit/89d1fee8a1547e90924155b26335b7041d25faf0

**Comment by stan0x** [comment]
Great haven't seen it crash on my servers ! Can u add this  so it will be more smooth for public servers.

* auto balance is not working. players can join same team then game stops and starts in warmup.  ( can be annoying with some people that have no respect )
* dm_shield should be enable while warmup is set to 1. ( so no spawn kills can be made. )
* spectating not working while players spawned in warmup mode.

**Comment by Raptor007** [comment]
Warmup also probably shouldn't add to player stats.

**Comment by Raptor007** [comment]
Warmup dm_shield: https://github.com/Raptor007/aq2-tng/commit/859e1ded4763b4dedf9e06e624f678589e9106c5
Don't change stats in warmup: https://github.com/Raptor007/aq2-tng/commit/62e468bb1d8340f8491c7c7d50b22d28ca2bd2b2
Always show death messages in warmup: https://github.com/Raptor007/aq2-tng/commit/d9b79b6cc3b8c311854d1ec6b2cafc1dc7b4e80f

**Comment by Raptor007** [comment]
I've opened a new issue for auto-balance: #55

So the last to-do item here is spectating warmup mode, which would be kind of messy, but I think it could be done.

**Comment by Raptor007** [comment]
I'm going to close this issue (since it contains a lot of unrelated chatter) and keep issue #126 open for spectating warmup.
