### ISSUE TITLE
Use map votes to select next map in rotation.

### ISSUE THREAD

**Issue by Raptor007** [Raptor007/aq2-tng#18]
If players voted on maps but not enough to change it, when the map ends the server should (optionally?) consider these votes when deciding which map to play next.

**Comment by Raptor007** [comment]
Added this feature in commit: https://github.com/Raptor007/aq2-tng/commit/a78334c2baa9ec58e04a84c295124c99e5be184c

There is currently no way to disable this by cvar, but I could easily add one if anyone would like that.  Let me know.

**Comment by stan0x** [comment]
raptor can u make a cvar to turn this function off ?

some people dont like it. so its best to make it a option i think.

**Comment by Raptor007** [comment]
Added `mapvote_next` cvar, default enabled: https://github.com/Raptor007/aq2-tng/commit/e0947e74d73d5beb6d2b5a97f36718c5f5954e34
Set `mapvote_next 0` to disable using the most voted map when the map ends.
