### ISSUE TITLE
'sv scramble' breaks teamdm

### ISSUE THREAD

**Issue by m4son** [Raptor007/aq2-tng#38]
While in teamdm mode teams are scrambled and players stay in observe mode, waiting for a round to start but teamdm has no rounds.

**Comment by Raptor007** [comment]
This is also true for ctf.

**Comment by Raptor007** [comment]
Fixed in commit: https://github.com/Raptor007/aq2-tng/commit/311ae06aff1dee0122e7b283d580a8b444ae4b4f
