### ISSUE TITLE
Let knives move with doors, and don't let doors crush items.

### ISSUE THREAD

**Issue by Raptor007** [Raptor007/aq2-tng#40]
_Original title: Allow knives to stay stuck in doors as they open/close._

If a throwing knife hits a door and then you open the door, the knife disappears.  Instead, it should move with the door, like splats and bullet holes now do: https://github.com/Raptor007/aq2-tng/commit/b153572f7a939c076b11cdbd94ba59a86036dbc2#diff-b29d7d7baca641fddebef179956b1547R868

**Comment by m4son** [comment]
weapons or items in front of the doors on the ground disappear too.

**Comment by Raptor007** [comment]
I think the reason items are disappearing is because the `item->pickup` function returns true for touching a door: https://github.com/Raptor007/aq2-tng/blob/master/source/g_items.c#L835

**Comment by Raptor007** [comment]
Wow, this one is more complicated than I thought it'd be!

Rotating doors have `ent->blocked = door_blocked`:
https://github.com/Raptor007/aq2-tng/blob/ce72b4a6a9a294568e529cf7a0c66bc7efe57c6e/source/g_func.c#L1403

The `door_blocked` function destroys items here:
https://github.com/Raptor007/aq2-tng/blob/ce72b4a6a9a294568e529cf7a0c66bc7efe57c6e/source/g_func.c#L1190

And the `ent->blocked` is only called from here:
https://github.com/Raptor007/aq2-tng/blob/ce72b4a6a9a294568e529cf7a0c66bc7efe57c6e/source/g_phys.c#L618

I _think_ `blocked` will only be called if `SV_Push` returns false:
https://github.com/Raptor007/aq2-tng/blob/ce72b4a6a9a294568e529cf7a0c66bc7efe57c6e/source/g_phys.c#L557

And that's probably caused by `SV_TestEntityPosition` returning true after the item is pushed:
https://github.com/Raptor007/aq2-tng/blob/ce72b4a6a9a294568e529cf7a0c66bc7efe57c6e/source/g_phys.c#L521

But I don't see anything obviously wrong with `SV_TestEntityPosition`:
https://github.com/Raptor007/aq2-tng/blob/ce72b4a6a9a294568e529cf7a0c66bc7efe57c6e/source/g_phys.c#L45

So it's possible the code to push things is wrong for the way rotating doors work:
https://github.com/Raptor007/aq2-tng/blob/ce72b4a6a9a294568e529cf7a0c66bc7efe57c6e/source/g_phys.c#L509

I could work around this for knives stuck in doors with a special `movetype` when stuck in a door:
https://github.com/Raptor007/aq2-tng/blob/ce72b4a6a9a294568e529cf7a0c66bc7efe57c6e/source/g_weapon.c#L1085

Specifically, one of these that `SV_Push` would ignore:
https://github.com/Raptor007/aq2-tng/blob/ce72b4a6a9a294568e529cf7a0c66bc7efe57c6e/source/g_phys.c#L468

But that wouldn't help with items on the floor, which should still be `MOVETYPE_TOSS` so they can be pushed around by map entities.

**Comment by Raptor007** [comment]
I think knives will need to be a special case, so they follow doors in both directions.

**Comment by Raptor007** [comment]
Special case for knives is done: https://github.com/Raptor007/aq2-tng/commit/800d0dfd45593dd1b19daf31a6740ab843d5e74f

**Comment by Raptor007** [comment]
I suspect `SV_TestEntityPosition` is always returning true for dropped items because `ent->mins[2]` is negative, which would make platforms think they are always trying and failing to push nearby items.  This would explain why throwing a knife anywhere near the spinning thing on q2dm5 makes it stop.

**Comment by m4son** [comment]
Not just knives, items and weapons infront of the doors **are nicely** pushed away, but if its pushed to a wall or its near door joint it still disappear e.g. map time

**Comment by Raptor007** [comment]
Thanks @m4son.  I won't focus so much on q2dm5 for my testing then, because pushing some items doesn't seem to work right on that map, but people don't usually play AQ2 on those maps.

It sounds like I might need to change items that are blocking a door to `MOVETYPE_NONE` instead of despawning them, unless it's special weapons in non-teamplay DM so they can reset if they fall into a crusher or something.

I wonder if it makes sense to rotate items (not players) when pushed by a rotating door/platform:
https://github.com/Raptor007/aq2-tng/commit/93a5b8bc8c501fd9fb04e71fdc0db1e89aa9643b#diff-b2716300bc34ebb58720c1eea37f2269R509
I think it would look cool.  :¬)

**Comment by Raptor007** [comment]
Doors should no longer squish items: https://github.com/Raptor007/aq2-tng/commit/2ea92463fece0f9d8c78c61a119400356dc5f61d

**Comment by Raptor007** [comment]
Tweaked to prevent floating items: https://github.com/Raptor007/aq2-tng/commit/1d13455b91ec7a18a2b39d1a721a0ecd5851e127
