### ISSUE TITLE
Ignoring

### ISSUE THREAD

**Issue by dynamic0** [Raptor007/aq2-tng#59]
When Player1 ignores Player2, Player1 should not see Player2's name changing messages nor hear his radiosounds. I also think that the notify that 'Player ignores you' is redundant.

**Comment by Raptor007** [comment]
For name changes, this broadcast will have to be changed to a loop over the list of possible message recipients: https://github.com/Raptor007/aq2-tng/blob/12e0a2d09b406133804aadc9c942be16e74db2d7/source/p_client.c#L2535

That means I could also prevent live players from seeing dead player name changes if `deadtalk` is turned off.

Radio should be easy, just need to add `if( ! IsInIgnoreList(ent,from) )` here: https://github.com/Raptor007/aq2-tng/blob/12e0a2d09b406133804aadc9c942be16e74db2d7/source/a_radio.c#L242

I think it should let you know when someone ignores you, as long as you aren't already ignoring them.

**Comment by Raptor007** [comment]
I think this should do the trick: https://github.com/Raptor007/aq2-tng/commit/92c419178e95ee67cd1412c6e601a7a9694abf56

**Comment by Raptor007** [comment]
The fix has been pushed upstream.  Reopen the issue if you find any problems with it.
