### ISSUE TITLE
dmweapon gives free weapon even if allweapon is 0

### ISSUE THREAD

**Issue by dynamic0** [Raptor007/aq2-tng#64]
In Deathmatchmode, even if allweapon is 0, and player should only have pistol and knife, the Player can get any weapon he wants at spawn by selecting it with the command 'dmweapon'. Also when playing with Bots, the Bots will get to use the weapon you have selected with dmweapon.

![aq2](https://user-images.githubusercontent.com/20885238/30785712-a0f2d084-a173-11e7-919f-0b30225354ed.png)

**Comment by Raptor007** [comment]
I think it's working as intended; `dmweapon` is a _server_ cvar that selects a weapon to spawn all deathmatch players with.  If you're the host, you have access to this variable.

The `allweapon` variable gives every player _all_ the weapons when they spawn.  You wouldn't need to use `dmweapon` in that case.

**Comment by dynamic0** [comment]
Okay. I thought this might be the case since dmweapon isn't accessible on public servers. 

Though I would like that there would be a clientside command to choose the weapon at spawn when allweapon is 1. 

This issue however can be scrapped.
