### ISSUE TITLE
Add option to force skin in deathmatch mode.

### ISSUE THREAD

**Issue by stan0x** [Raptor007/aq2-tng#69]
Is it possible to add a option to force a skin in deathmatch mode so everyone has the same skin ?

set force_skin "male/ctf_r"

**Comment by Raptor007** [comment]
That sounds pretty easy!  I'll look into it.

**Comment by Raptor007** [comment]
Done, mostly by stan0x: https://github.com/Raptor007/aq2-tng/commit/641aca6b3a629cc42d6c32274989b1e6877a75af https://github.com/Raptor007/aq2-tng/commit/c5a60c35431eb87707824ab5d362707c0f7ed9eb https://github.com/Raptor007/aq2-tng/commit/32d3f9ac5acd33892a3a6d835fa43e5acbdebcb9 https://github.com/Raptor007/aq2-tng/commit/6099b232796a5bc4d9ffeaec741c6e5a5c110370
