### ISSUE TITLE
sv addbot, bot amount parameters?

### ISSUE THREAD

**Issue by dynamic0** [Raptor007/aq2-tng#76]
**sv addbot 1 3** adds 1 bot named "3" to team 1. 

Instead of **sv addbot [team] [name]** could it be: 

**sv addbot [team] [amount] [name]** 

or check if the second parameter has numbers or letters:

**sv addbot [team] [amount/name]** 

When added more than 1 bot, generate random names for the bots.

**Comment by Raptor007** [comment]
I would rather not change and complicate the existing behavior, but how about a new addbots command that always uses random names?

`sv addbots [qty]`  add [qty] bots, auto-assign team if teamplay

`sv addbots [qty] [team]`  add [qty] bots to [team]

**Comment by dynamic0** [comment]
Seems like a good idea! 👍

**Comment by Raptor007** [comment]
Done, and pushed this update to main aq2-tng.
