### ISSUE TITLE
Matchmode is broken when teams switch in ctf half of the map

### ISSUE THREAD

**Issue by stan0x** [Raptor007/aq2-tng#80]
When playing ctf in matchmode. the teams switch half of the map time. Then captains are broken en teams stay ready. Its not posible to claim captain status en unready teams. Its look like when teams switched side they lose captain status.

**Comment by Raptor007** [comment]
I believe this was fixed by https://github.com/Raptor007/aq2-tng/commit/907e078717004138548dce74441589119fde1e1b last year; please re-open the issue if I'm wrong.  Thanks!
