### ISSUE TITLE
Zip Release of AQ2 Paks and DLL

### ISSUE THREAD

**Issue by Raptor007** [Raptor007/aq2-tng#85]
Some people have been reporting issues with Q2Online, and the old AQ2 1.52 client install is hard to find.  I think it's time to make a new easy zip archive of the **action** directory for people who already have Quake2 installed, containing the basics needed to play.

**Comment by darkshade9** [comment]
We're starting a project now to handle this:

https://github.com/actionquake/distrib

**Comment by Raptor007** [comment]
Yours is probably a better way to do it for new players and I encourage you to keep at it.

Even so, I'd also like to create an action folder zip that can be dropped into any existing Quake 2 install, such as the Steam, GOG, and RTX versions of Quake II.  Maybe I'm just old fashioned.  But first I'll clear a few more bugs off the list and maybe bump the version to 2.82.

**Comment by darkshade9** [comment]
I can create a 'drag and drop' add-on release tarball/zip for existing installations with instructions on how to launch it (+set game action), it makes sense for RTX and people who love other clients like Yamagi and don't want to install a client just for AQ2.

**Comment by darkshade9** [comment]
We have a regular cadence of releases now
https://github.com/actionquake/distrib/releases

This includes Mac M1, Mac Intel, 64-bit x86 Linux and Windows, 64-bit ARM Linux and 32-bit Windows.  It also includes a content-only zip that can be used for existing installations as a drag-n-drop install, and server-only files for 64-bit x86 and ARM Linux with q2admin.  All are built from source on the `aqtion` branch of [q2pro](https://github.com/actionquake/q2pro), the `aqtion` branch of [aq2-tng](https://github.com/actionquake/aq2-tng) (this repository) and the `aqtion` branch of [q2admin](https://github.com/actionquake/q2admin)

If this all fits the bill for a ready-to-go installation, we could consider this issue resolved?

**Comment by darkshade9** [comment]
I think since AQtion is released, we can probably close this out?

**Comment by Raptor007** [comment]
Hah yeah it does seem less relevant now.  New players are almost surely using AQtion rather than unzipping AQ2 into a fresh Quake 2 install.
