### ISSUE TITLE
Animations with sv_fps

### ISSUE THREAD

**Issue by Raptor007** [Raptor007/aq2-tng#86]
Anything that changes `ent->s.frame` should also update `ent->client->anim_framesync` to ensure animations don't advance too quickly to their second frame at higher server framerates.

This could probably be solved with a new function replacing all raw animation changes:

    void SetAnimation( edict_t *ent, int frame, int anim_end, int anim_priority )
    {
        ent->s.frame = frame;
        ent->client->anim_end = anim_end;
        ent->client->anim_priority = anim_priority;
        ent->client->anim_framesync = level.framenum % game.framediv;
    }

**Comment by Raptor007** [comment]
Might also be useful to change `anim_framesync` to `anim_started` and use it to prevent people from switching back and forth from crouch to stand faster than 10 times per second.

**Comment by Raptor007** [comment]
I think this should do the trick:
https://github.com/Raptor007/aq2-tng/commit/e5a7bb7f62c127907ef1cadfd6b4bafa9a0b1d11

**Comment by m4son** [comment]
I tried spamming spacebar (jump) while holding crouch and animation played back nicely at low 10 frame rate with a sv_fps 60
